name: Test Runner

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo "Hallo vom Rezepte-Runner!"

      - name: Build Docker Image
        run: docker build -t rezepte-test .
