name: Test Runner

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Version
        run: docker --version

      - name: Test
        run: echo "Hallo vom Rezepte-Runner!"
